# NUMPY библиотека

In [2]:
import numpy as np
a = [i for i in range(10)]

In [3]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
b = np.array(a)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
b = np.array([0,1,2,3,4,5])
b

array([0, 1, 2, 3, 4, 5])

In [6]:
b = np.array([i for i in range(10)])
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
floatArray = np.array(a,dtype=float)
floatArray

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
intArray = np.array(a,dtype=int)
intArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
strArray = np.array(a,dtype=str) # if one element is float all elements are float
strArray

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U1')

strArray[0] #indexation

array.dtype -showing the array type

b.ndim, b.shape

In [10]:
b = np.array ([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [11]:
b.shape

(2, 2)

In [12]:
b.ndim

2

In [13]:
b.size

4

In [14]:
b[0][0]

1

In [15]:
b[0,0]

1

In [60]:
# Cutting from array:
# The first cut is applied to the first array ('rows')
# The second cut is applied to the second array ('columns')
b[0:2,1:2]

array([[2],
       [4]])

In [23]:
x = b.copy()
x

array([[1, 2],
       [3, 4]])

dtype = np.int(32)
dtype = np.int(64)
dtype = np.float(32)
dtype = np.float(64)

In [24]:
# The basic operator + works as a combination of two arrays
x1=[1,2]
x2=[2,3]
x = x2+x1
x

[2, 3, 1, 2]

In [25]:
# The np arrays + works as a SUM of two arrays
x1= np.array(x1)
x2= np.array(x2)
x = x2+x1
x

array([3, 5])

In [28]:
# The difference between np arrays
x = x2-x1
x

array([1, 1])

In [29]:
# Adding by function:
np.add(x2,x1)

array([3, 5])

In [30]:
# Subtracting by function:
np.subtract(x1,x2)

array([-1, -1])

In [44]:
# Multiplying arrays:
c = x1*2
c

array([2, 4])

In [47]:
c =x1*-10
c

array([-10, -20])

In [49]:
c=c.dot(-10)
c

array([100, 200])

In [50]:
# Scalar multiplying:
x1 @ x2

8

In [51]:
# Scalar multiplying:
x1.dot(x2)

8

In [31]:
# Multidimension sum:
A = np.array([[1,2],[2,3]])
B = np.array([[3,2],[2,1]])
A+B

array([[4, 4],
       [4, 4]])

In [32]:
# Multidimension subtract:
A - B

array([[-2,  0],
       [ 0,  2]])

In [33]:
# Multidimension multiplicator:
A*2

array([[2, 4],
       [4, 6]])

In [57]:
A.dot(2)

array([[2, 4],
       [4, 6]])

In [58]:
A.dot(B)

array([[ 7,  4],
       [12,  7]])

In [59]:
A @ B

array([[ 7,  4],
       [12,  7]])

In [60]:
np.dot(A,B)

array([[ 7,  4],
       [12,  7]])

In [61]:
A.shape

(2, 2)

# Модуль numpy.linalg

In [35]:
import numpy.linalg

A = np.array([[1,2],[2,3]])

# Матричное умножение A*A:
np.dot(A,A)

array([[ 5,  8],
       [ 8, 13]])

In [36]:
# Матричное умножение на linalg
np.linalg.matrix_power(A,2)

array([[ 5,  8],
       [ 8, 13]])

In [37]:
# Единичная матрица
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [67]:
# Транспонированная матрица 1
A.transpose()

array([[1, 2],
       [2, 3]])

In [68]:
# Транспонированная матрица 2
A.T

array([[1, 2],
       [2, 3]])

In [38]:
# Умножение матриц оператором
A @ I

array([[1., 2.],
       [2., 3.]])

In [39]:
# Определитель матрицы
np.linalg.det(A)

-1.0

In [40]:
# Ранг матрицы
np.linalg.matrix_rank(A)

2

In [41]:
# Обратная матрица
np.linalg.inv(A)

array([[-3.,  2.],
       [ 2., -1.]])

In [42]:
# Обратная матрица умноженная на себя дает единичную матрицу
np.linalg.inv(A) @ A

array([[1., 0.],
       [0., 1.]])

In [43]:
# Генерация массива нулей
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
# Генерация массива единиц
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [46]:
np.linspace(0,9.9,100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [47]:
np.random.sample()

0.7248446171470231

In [48]:
np.random.sample((2,3))

array([[0.15027552, 0.53505233, 0.41798857],
       [0.70166425, 0.91288642, 0.17973161]])

In [49]:
np.random.randn(3,4)

array([[-0.4473161 ,  0.00533152,  0.94031977,  0.28748617],
       [ 1.06178918, -0.42980302,  0.18419838, -0.00683571],
       [ 0.52047085, -0.97735446, -0.53169519, -0.23600308]])

In [50]:
np.random.randint(3,4)

3

In [51]:
np.random.choice(a)

5

In [52]:
np.random.seed(34)
np.random.randn(3,4)

array([[ 0.2438351 , -0.74731818, -1.56117699, -0.46425312],
       [-0.35206234, -1.28149188,  0.28929924,  0.9800285 ],
       [ 0.47792422,  0.45081813,  0.75244345, -0.51057179]])

In [53]:
np.random.choice(a,3)

array([4, 8, 4])

In [56]:
np.random.sample((2,3)).flatten()

array([0.86146918, 0.3336597 , 0.41520666, 0.42760915, 0.99808623,
       0.7037764 ])

In [57]:
np.vsstuck(a,b)

AttributeError: module 'numpy' has no attribute 'vsstuck'

In [ ]:
np.hstack(a,b)

In [25]:
a = np.random.randint(0,10,20)
a

array([4, 2, 5, 2, 2, 9, 6, 8, 2, 6, 0, 5, 4, 0, 4, 4, 9, 7, 4, 9])

In [26]:
a[a>10]

array([], dtype=int32)

In [27]:
a[(a>3) & (a % 2 ==0)] 

array([4, 6, 8, 6, 4, 4, 4, 4])

In [28]:
a[np.where(a>3)]

array([4, 5, 9, 6, 8, 6, 5, 4, 4, 4, 9, 7, 4, 9])

In [29]:
a=np.array([1,3])
b=np.array([2,3])
np.where([True,False,],a,b)

array([1, 3])

In [34]:
a=a.argsort(axis = 0)

array([1, 0], dtype=int64)

In [53]:
a=np.array ([[1,3,10],[6,2,3]])
#a=a[a.argsort(axis=0)]
a[:,0].argsort()

array([0, 1], dtype=int64)

In [55]:
a[a[:,1].argsort(),:]

array([[ 6,  2,  3],
       [ 1,  3, 10]])

In [58]:
np.random.shuffle(a)


TypeError: object of type 'NoneType' has no len()

In [12]:
a.sum()

4

In [60]:
a=np.array([1,23])
np.log(a)

array([0.        , 3.13549422])

In [61]:
np.exp(a)

array([2.71828183e+00, 9.74480345e+09])

In [13]:
a+10

array([13, 11])

In [62]:
np.sum(a)

24

In [63]:
a=np.array([1,2,3])
b=np.array([1,3,2])
a*b

array([1, 6, 6])

In [64]:
a = np.array([[1,2],[3,4],[1,2]])
b = np.array([1,2])
a+b

array([[2, 4],
       [4, 6],
       [2, 4]])

In [65]:
c = np.array([[1],[2],[1]])
a+b+c

array([[3, 5],
       [6, 8],
       [3, 5]])

In [66]:
c.min()

1

In [67]:
a.min()

1

In [68]:
a.max()

4

In [71]:
a.min(axix = 1)

TypeError: _amin() got an unexpected keyword argument 'axix'

In [72]:
a.mean()

2.1666666666666665

In [73]:
a.std()

1.0671873729054748

In [75]:
np.save('a.npy',a)

In [77]:
np.load('a.npy')


array([[1, 2],
       [3, 4],
       [1, 2]])